### ISSUE TITLE
Command "unset PATH; ls" should print an error message: ls: No such file or directory

### ISSUE THREAD

**Issue by maxbipboop** [sophiakoulen/minishell#87]

**Comment by sophiakoulen** [comment]
In Bash, when you unset PATH, no commands are found. However, if you start bash in an environment that has no PATH, a default PATH is used.
You can see the contents of that default PATH using echo $PATH, but it is not shown in env or export. This is because (i think), that default PATH is a shell variable. If you export PATH, then it is in the environment.

Mimicking this exact behaviour might be tricky, because we can't just add a default PATH to the environment at initialization if we want to be exact.
If we want to be exact, we'll need to keep track of a second set of variable: the shell variables.
Export, unset, expansion and command finding would need to be aware of these shell variables.

We could also just use a flag defaultPath that tells us whether or not we should look into a default path if no PATH is found. It is however difficult to be exact with this method, since it would make echoing $PATH when no env PATH is set tricky.
We'd need a conditional statement only for when the variable we are expanding is PATH, which is quite ugly.

Implementing shell variables could be interesting! It adds extra parsing though. But it's a great feature.
